//
// File generated by rootcint at Mon May 20 15:08:34 2013

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME COINCEventDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "COINCEventDict.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void COINCEvent_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_COINCEvent(void *p = 0);
   static void *newArray_COINCEvent(Long_t size, void *p);
   static void delete_COINCEvent(void *p);
   static void deleteArray_COINCEvent(void *p);
   static void destruct_COINCEvent(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::COINCEvent*)
   {
      ::COINCEvent *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::COINCEvent >(0);
      static ::ROOT::TGenericClassInfo 
         instance("COINCEvent", ::COINCEvent::Class_Version(), "./COINCEvent.hh", 8,
                  typeid(::COINCEvent), DefineBehavior(ptr, ptr),
                  &::COINCEvent::Dictionary, isa_proxy, 4,
                  sizeof(::COINCEvent) );
      instance.SetNew(&new_COINCEvent);
      instance.SetNewArray(&newArray_COINCEvent);
      instance.SetDelete(&delete_COINCEvent);
      instance.SetDeleteArray(&deleteArray_COINCEvent);
      instance.SetDestructor(&destruct_COINCEvent);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::COINCEvent*)
   {
      return GenerateInitInstanceLocal((::COINCEvent*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::COINCEvent*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *COINCEvent::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *COINCEvent::Class_Name()
{
   return "COINCEvent";
}

//______________________________________________________________________________
const char *COINCEvent::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::COINCEvent*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int COINCEvent::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::COINCEvent*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void COINCEvent::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::COINCEvent*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *COINCEvent::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::COINCEvent*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void COINCEvent::Streamer(TBuffer &R__b)
{
   // Stream an object of class COINCEvent.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(COINCEvent::Class(),this);
   } else {
      R__b.WriteClassBuffer(COINCEvent::Class(),this);
   }
}

//______________________________________________________________________________
void COINCEvent::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class COINCEvent.
      TClass *R__cl = ::COINCEvent::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "charge", (void*)&charge);
      R__insp.InspectMember("vector<double>", (void*)&charge, "charge.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "chargeGC", (void*)&chargeGC);
      R__insp.InspectMember("vector<double>", (void*)&chargeGC, "chargeGC.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "energyLYSO", &energyLYSO);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "energyGC", &energyGC);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "timestampLYSO", &timestampLYSO);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "timestampLYSONS", &timestampLYSONS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "gaussXPos", &gaussXPos);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "gaussYPos", &gaussYPos);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "gaussSXPos", &gaussSXPos);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "gaussSYPos", &gaussSYPos);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "lercheXPos", &lercheXPos);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "lercheYPos", &lercheYPos);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "chi2XPos", (void*)&chi2XPos);
      R__insp.InspectMember("vector<double>", (void*)&chi2XPos, "chi2XPos.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "chi2YPos", (void*)&chi2YPos);
      R__insp.InspectMember("vector<double>", (void*)&chi2YPos, "chi2YPos.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "chi2LXPos", (void*)&chi2LXPos);
      R__insp.InspectMember("vector<double>", (void*)&chi2LXPos, "chi2LXPos.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "chi2LYPos", (void*)&chi2LYPos);
      R__insp.InspectMember("vector<double>", (void*)&chi2LYPos, "chi2LYPos.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "errInput", &errInput);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "errOutOfRange", &errOutOfRange);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nSlidePos", &nSlidePos);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "energyFirst", &energyFirst);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "energyMax", &energyMax);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "energyGE", &energyGE);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "timestampGE", &timestampGE);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "timestampGENS", &timestampGENS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "timestampT50", &timestampT50);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "timestampT50NS", &timestampT50NS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "T50Offset", &T50Offset);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "T50OffsetNS", &T50OffsetNS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "wfRaw", (void*)&wfRaw);
      R__insp.InspectMember("vector<double>", (void*)&wfRaw, "wfRaw.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "wfEnergy", (void*)&wfEnergy);
      R__insp.InspectMember("vector<double>", (void*)&wfEnergy, "wfEnergy.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "wfDiff", (void*)&wfDiff);
      R__insp.InspectMember("vector<double>", (void*)&wfDiff, "wfDiff.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "IMax", &IMax);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "channel", &channel);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_COINCEvent(void *p) {
      return  p ? new(p) ::COINCEvent : new ::COINCEvent;
   }
   static void *newArray_COINCEvent(Long_t nElements, void *p) {
      return p ? new(p) ::COINCEvent[nElements] : new ::COINCEvent[nElements];
   }
   // Wrapper around operator delete
   static void delete_COINCEvent(void *p) {
      delete ((::COINCEvent*)p);
   }
   static void deleteArray_COINCEvent(void *p) {
      delete [] ((::COINCEvent*)p);
   }
   static void destruct_COINCEvent(void *p) {
      typedef ::COINCEvent current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::COINCEvent

namespace ROOT {
   void vectorlEdoublegR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEdoublegR_Dictionary();
   static void *new_vectorlEdoublegR(void *p = 0);
   static void *newArray_vectorlEdoublegR(Long_t size, void *p);
   static void delete_vectorlEdoublegR(void *p);
   static void deleteArray_vectorlEdoublegR(void *p);
   static void destruct_vectorlEdoublegR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<double>*)
   {
      vector<double> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<double>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<double>", -2, "vector.dll", 0,
                  typeid(vector<double>), DefineBehavior(ptr, ptr),
                  0, &vectorlEdoublegR_Dictionary, isa_proxy, 0,
                  sizeof(vector<double>) );
      instance.SetNew(&new_vectorlEdoublegR);
      instance.SetNewArray(&newArray_vectorlEdoublegR);
      instance.SetDelete(&delete_vectorlEdoublegR);
      instance.SetDeleteArray(&deleteArray_vectorlEdoublegR);
      instance.SetDestructor(&destruct_vectorlEdoublegR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<double> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<double>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEdoublegR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<double>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlEdoublegR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<double> : new vector<double>;
   }
   static void *newArray_vectorlEdoublegR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<double>[nElements] : new vector<double>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEdoublegR(void *p) {
      delete ((vector<double>*)p);
   }
   static void deleteArray_vectorlEdoublegR(void *p) {
      delete [] ((vector<double>*)p);
   }
   static void destruct_vectorlEdoublegR(void *p) {
      typedef vector<double> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<double>

/********************************************************
* COINCEventDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableCOINCEventDict();

extern "C" void G__set_cpp_environmentCOINCEventDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("COINCEvent.hh");
  G__cpp_reset_tagtableCOINCEventDict();
}
#include <new>
extern "C" int G__cpp_dllrevCOINCEventDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* COINCEvent */
static int G__COINCEventDict_656_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   COINCEvent* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new COINCEvent[n];
     } else {
       p = new((void*) gvp) COINCEvent[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new COINCEvent;
     } else {
       p = new((void*) gvp) COINCEvent;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__COINCEventDictLN_COINCEvent));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   COINCEvent* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 2
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new COINCEvent((LYSOEvent*) G__int(libp->para[0]), (GEEvent*) G__int(libp->para[1]));
   } else {
     p = new((void*) gvp) COINCEvent((LYSOEvent*) G__int(libp->para[0]), (GEEvent*) G__int(libp->para[1]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__COINCEventDictLN_COINCEvent));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<double>* pobj;
         vector<double> xobj = ((COINCEvent*) G__getstructoffset())->GetCharge();
         pobj = new vector<double>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<double>* pobj;
         vector<double> xobj = ((COINCEvent*) G__getstructoffset())->GetChargeGC();
         pobj = new vector<double>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((COINCEvent*) G__getstructoffset())->GetEnergyLYSO());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((COINCEvent*) G__getstructoffset())->GetEnergyGC());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      G__letdouble(result7, 100, (double) ((COINCEvent*) G__getstructoffset())->GetTimestampLYSO((bool) G__int(libp->para[0])));
      break;
   case 0:
      G__letdouble(result7, 100, (double) ((COINCEvent*) G__getstructoffset())->GetTimestampLYSO());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((COINCEvent*) G__getstructoffset())->GetGaussXPos());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((COINCEvent*) G__getstructoffset())->GetGaussYPos());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((COINCEvent*) G__getstructoffset())->GetGaussSXPos());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((COINCEvent*) G__getstructoffset())->GetGaussSYPos());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((COINCEvent*) G__getstructoffset())->GetLercheXPos());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((COINCEvent*) G__getstructoffset())->GetLercheYPos());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<double>* pobj;
         vector<double> xobj = ((COINCEvent*) G__getstructoffset())->GetChi2XPos();
         pobj = new vector<double>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<double>* pobj;
         vector<double> xobj = ((COINCEvent*) G__getstructoffset())->GetChi2YPos();
         pobj = new vector<double>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<double>* pobj;
         vector<double> xobj = ((COINCEvent*) G__getstructoffset())->GetChi2LXPos();
         pobj = new vector<double>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<double>* pobj;
         vector<double> xobj = ((COINCEvent*) G__getstructoffset())->GetChi2LYPos();
         pobj = new vector<double>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((COINCEvent*) G__getstructoffset())->ErrInput());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((COINCEvent*) G__getstructoffset())->ErrOutOfRange());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((COINCEvent*) G__getstructoffset())->GetNSlidePos());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((COINCEvent*) G__getstructoffset())->GetEnergyGE());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((COINCEvent*) G__getstructoffset())->GetEnergyMax());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((COINCEvent*) G__getstructoffset())->GetEnergyFirst());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      G__letdouble(result7, 100, (double) ((COINCEvent*) G__getstructoffset())->GetTimestampGE((bool) G__int(libp->para[0])));
      break;
   case 0:
      G__letdouble(result7, 100, (double) ((COINCEvent*) G__getstructoffset())->GetTimestampGE());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      G__letdouble(result7, 100, (double) ((COINCEvent*) G__getstructoffset())->GetTimestampT50((bool) G__int(libp->para[0])));
      break;
   case 0:
      G__letdouble(result7, 100, (double) ((COINCEvent*) G__getstructoffset())->GetTimestampT50());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      G__letdouble(result7, 100, (double) ((COINCEvent*) G__getstructoffset())->GetT50Offset((bool) G__int(libp->para[0])));
      break;
   case 0:
      G__letdouble(result7, 100, (double) ((COINCEvent*) G__getstructoffset())->GetT50Offset());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<double>* pobj;
         vector<double> xobj = ((COINCEvent*) G__getstructoffset())->GetWFRaw();
         pobj = new vector<double>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<double>* pobj;
         vector<double> xobj = ((COINCEvent*) G__getstructoffset())->GetWFEnergy();
         pobj = new vector<double>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<double>* pobj;
         vector<double> xobj = ((COINCEvent*) G__getstructoffset())->GetWFDiff();
         pobj = new vector<double>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((COINCEvent*) G__getstructoffset())->GetIMax());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((COINCEvent*) G__getstructoffset())->GetChannel());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((COINCEvent*) G__getstructoffset())->SetCharge(*((vector<double>*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((COINCEvent*) G__getstructoffset())->SetChargeGC(*((vector<double>*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((COINCEvent*) G__getstructoffset())->SetEnergyLYSO((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((COINCEvent*) G__getstructoffset())->SetEnergyGC((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((COINCEvent*) G__getstructoffset())->SetTimestampLYSO((double) G__double(libp->para[0]), (bool) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((COINCEvent*) G__getstructoffset())->SetTimestampLYSO((double) G__double(libp->para[0]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((COINCEvent*) G__getstructoffset())->SetGaussXPos((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((COINCEvent*) G__getstructoffset())->SetGaussYPos((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((COINCEvent*) G__getstructoffset())->SetGaussSXPos((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((COINCEvent*) G__getstructoffset())->SetGaussSYPos((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_41(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((COINCEvent*) G__getstructoffset())->SetLercheXPos((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_42(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((COINCEvent*) G__getstructoffset())->SetLercheYPos((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_43(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((COINCEvent*) G__getstructoffset())->SetChi2XPos(*((vector<double>*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_44(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((COINCEvent*) G__getstructoffset())->SetChi2YPos(*((vector<double>*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_45(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((COINCEvent*) G__getstructoffset())->SetChi2LXPos(*((vector<double>*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_46(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((COINCEvent*) G__getstructoffset())->SetChi2LYPos(*((vector<double>*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_47(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((COINCEvent*) G__getstructoffset())->SetErrInput((bool) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_48(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((COINCEvent*) G__getstructoffset())->SetErrOutOfRange((bool) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_49(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((COINCEvent*) G__getstructoffset())->SetNSlidePos((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_50(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((COINCEvent*) G__getstructoffset())->SetEnergyGE((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_51(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((COINCEvent*) G__getstructoffset())->SetEnergyMax((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_52(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((COINCEvent*) G__getstructoffset())->SetEnergyFirst((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_53(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((COINCEvent*) G__getstructoffset())->SetTimestampGE((double) G__double(libp->para[0]), (bool) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((COINCEvent*) G__getstructoffset())->SetTimestampGE((double) G__double(libp->para[0]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_54(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((COINCEvent*) G__getstructoffset())->SetTimestampT50((double) G__double(libp->para[0]), (bool) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((COINCEvent*) G__getstructoffset())->SetTimestampT50((double) G__double(libp->para[0]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_55(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((COINCEvent*) G__getstructoffset())->SetT50Offset((double) G__double(libp->para[0]), (bool) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((COINCEvent*) G__getstructoffset())->SetT50Offset((double) G__double(libp->para[0]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_56(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((COINCEvent*) G__getstructoffset())->SetWFRaw(*((vector<double>*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_57(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((COINCEvent*) G__getstructoffset())->SetWFEnergy(*((vector<double>*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_58(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((COINCEvent*) G__getstructoffset())->SetWFDiff(*((vector<double>*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_59(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((COINCEvent*) G__getstructoffset())->SetIMax((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_60(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((COINCEvent*) G__getstructoffset())->SetChannel((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_61(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((COINCEvent*) G__getstructoffset())->CopyEvents((LYSOEvent*) G__int(libp->para[0]), (GEEvent*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_62(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((COINCEvent*) G__getstructoffset())->CalcT1ToT2TimeNS((double) G__double(libp->para[0]), (double) G__double(libp->para[1])
, *(double*) G__Doubleref(&libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_63(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((COINCEvent*) G__getstructoffset())->Clear();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_64(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) COINCEvent::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_65(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) COINCEvent::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_66(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) COINCEvent::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_67(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      COINCEvent::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_71(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((COINCEvent*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_72(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) COINCEvent::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_73(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) COINCEvent::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_74(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) COINCEvent::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__COINCEventDict_656_0_75(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) COINCEvent::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__COINCEventDict_656_0_76(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   COINCEvent* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new COINCEvent(*(COINCEvent*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__COINCEventDictLN_COINCEvent));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef COINCEvent G__TCOINCEvent;
static int G__COINCEventDict_656_0_77(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (COINCEvent*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((COINCEvent*) (soff+(sizeof(COINCEvent)*i)))->~G__TCOINCEvent();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (COINCEvent*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((COINCEvent*) (soff))->~G__TCOINCEvent();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__COINCEventDict_656_0_78(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   COINCEvent* dest = (COINCEvent*) G__getstructoffset();
   *dest = *(COINCEvent*) libp->para[0].ref;
   const COINCEvent& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* COINCEvent */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncCOINCEventDict {
 public:
  G__Sizep2memfuncCOINCEventDict(): p(&G__Sizep2memfuncCOINCEventDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncCOINCEventDict::*p)();
};

size_t G__get_sizep2memfuncCOINCEventDict()
{
  G__Sizep2memfuncCOINCEventDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceCOINCEventDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__COINCEventDictLN_COINCEvent))) {
     COINCEvent *G__Lderived;
     G__Lderived=(COINCEvent*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__COINCEventDictLN_COINCEvent),G__get_linked_tagnum(&G__COINCEventDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableCOINCEventDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__COINCEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__COINCEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__COINCEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__COINCEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__COINCEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__COINCEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__COINCEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__COINCEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__COINCEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__COINCEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__COINCEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__COINCEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__COINCEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__COINCEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__COINCEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__COINCEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__COINCEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__COINCEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__COINCEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<UInt_t,Int_t>",117,G__get_linked_tagnum(&G__COINCEventDictLN_pairlEunsignedsPintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__COINCEventDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__COINCEventDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__COINCEventDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__COINCEventDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__COINCEventDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__COINCEventDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned int,int> >",117,G__get_linked_tagnum(&G__COINCEventDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__COINCEventDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__COINCEventDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__COINCEventDictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__COINCEventDictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* COINCEvent */
static void G__setup_memvarCOINCEvent(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__COINCEventDictLN_COINCEvent));
   { COINCEvent *p; p=(COINCEvent*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__COINCEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,2,"charge=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__COINCEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,2,"chargeGC=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"energyLYSO=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"energyGC=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"timestampLYSO=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"timestampLYSONS=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"gaussXPos=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"gaussYPos=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"gaussSXPos=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"gaussSYPos=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"lercheXPos=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"lercheYPos=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__COINCEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,2,"chi2XPos=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__COINCEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,2,"chi2YPos=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__COINCEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,2,"chi2LXPos=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__COINCEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,2,"chi2LYPos=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,2,"errInput=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,2,"errOutOfRange=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"nSlidePos=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"energyFirst=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"energyMax=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"energyGE=",0,"energyMax - energyFirst");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"timestampGE=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"timestampGENS=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"timestampT50=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"timestampT50NS=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"T50Offset=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"T50OffsetNS=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__COINCEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,2,"wfRaw=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__COINCEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,2,"wfEnergy=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__COINCEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,2,"wfDiff=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"IMax=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"channel=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__COINCEventDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarCOINCEventDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncCOINCEvent(void) {
   /* COINCEvent */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__COINCEventDictLN_COINCEvent));
   G__memfunc_setup("COINCEvent",878,G__COINCEventDict_656_0_1, 105, G__get_linked_tagnum(&G__COINCEventDictLN_COINCEvent), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("COINCEvent",878,G__COINCEventDict_656_0_2, 105, G__get_linked_tagnum(&G__COINCEventDictLN_COINCEvent), -1, 0, 2, 1, 1, 0, 
"U 'LYSOEvent' - 0 - newLYSO U 'GEEvent' - 0 - newGE", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCharge",874,G__COINCEventDict_656_0_3, 117, G__get_linked_tagnum(&G__COINCEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR), G__defined_typename("vector<double>"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetChargeGC",1012,G__COINCEventDict_656_0_4, 117, G__get_linked_tagnum(&G__COINCEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR), G__defined_typename("vector<double>"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetEnergyLYSO",1233,G__COINCEventDict_656_0_5, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetEnergyGC",1044,G__COINCEventDict_656_0_6, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTimestampLYSO",1563,G__COINCEventDict_656_0_7, 100, -1, -1, 0, 1, 1, 1, 0, "g - - 0 'false' inNanoSecs", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetGaussXPos",1197,G__COINCEventDict_656_0_8, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetGaussYPos",1198,G__COINCEventDict_656_0_9, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetGaussSXPos",1280,G__COINCEventDict_656_0_10, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetGaussSYPos",1281,G__COINCEventDict_656_0_11, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetLercheXPos",1277,G__COINCEventDict_656_0_12, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetLercheYPos",1278,G__COINCEventDict_656_0_13, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetChi2XPos",1008,G__COINCEventDict_656_0_14, 117, G__get_linked_tagnum(&G__COINCEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR), G__defined_typename("vector<double>"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetChi2YPos",1009,G__COINCEventDict_656_0_15, 117, G__get_linked_tagnum(&G__COINCEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR), G__defined_typename("vector<double>"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetChi2LXPos",1084,G__COINCEventDict_656_0_16, 117, G__get_linked_tagnum(&G__COINCEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR), G__defined_typename("vector<double>"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetChi2LYPos",1085,G__COINCEventDict_656_0_17, 117, G__get_linked_tagnum(&G__COINCEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR), G__defined_typename("vector<double>"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ErrInput",825,G__COINCEventDict_656_0_18, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ErrOutOfRange",1283,G__COINCEventDict_656_0_19, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetNSlidePos",1169,G__COINCEventDict_656_0_20, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetEnergyGE",1046,G__COINCEventDict_656_0_21, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetEnergyMax",1200,G__COINCEventDict_656_0_22, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetEnergyFirst",1426,G__COINCEventDict_656_0_23, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTimestampGE",1376,G__COINCEventDict_656_0_24, 100, -1, -1, 0, 1, 1, 1, 0, "g - - 0 'false' inNanoSecs", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTimestampT50",1421,G__COINCEventDict_656_0_25, 100, -1, -1, 0, 1, 1, 1, 0, "g - - 0 'false' inNanoSecs", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetT50Offset",1088,G__COINCEventDict_656_0_26, 100, -1, -1, 0, 1, 1, 1, 0, "g - - 0 'false' inNanoSecs", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetWFRaw",743,G__COINCEventDict_656_0_27, 117, G__get_linked_tagnum(&G__COINCEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR), G__defined_typename("vector<double>"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetWFEnergy",1063,G__COINCEventDict_656_0_28, 117, G__get_linked_tagnum(&G__COINCEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR), G__defined_typename("vector<double>"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetWFDiff",822,G__COINCEventDict_656_0_29, 117, G__get_linked_tagnum(&G__COINCEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR), G__defined_typename("vector<double>"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetIMax",655,G__COINCEventDict_656_0_30, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetChannel",985,G__COINCEventDict_656_0_31, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetCharge",886,G__COINCEventDict_656_0_32, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<double,allocator<double> >' 'vector<double>' 0 - newCharge", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetChargeGC",1024,G__COINCEventDict_656_0_33, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<double,allocator<double> >' 'vector<double>' 0 - newChargeGC", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetEnergyLYSO",1245,G__COINCEventDict_656_0_34, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - newEnergy", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetEnergyGC",1056,G__COINCEventDict_656_0_35, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - newEnergyGC", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTimestampLYSO",1575,G__COINCEventDict_656_0_36, 121, -1, -1, 0, 2, 1, 1, 0, 
"d - - 0 - newTimestampNS g - - 0 'false' inNanoSecs", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetGaussXPos",1209,G__COINCEventDict_656_0_37, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - newGaussXPos", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetGaussYPos",1210,G__COINCEventDict_656_0_38, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - newGaussYPos", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetGaussSXPos",1292,G__COINCEventDict_656_0_39, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - newGaussSXPos", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetGaussSYPos",1293,G__COINCEventDict_656_0_40, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - newGaussSYPos", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetLercheXPos",1289,G__COINCEventDict_656_0_41, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - newLercheXPos", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetLercheYPos",1290,G__COINCEventDict_656_0_42, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - newLercheYPos", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetChi2XPos",1020,G__COINCEventDict_656_0_43, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<double,allocator<double> >' 'vector<double>' 0 - newChi2XPos", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetChi2YPos",1021,G__COINCEventDict_656_0_44, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<double,allocator<double> >' 'vector<double>' 0 - newChi2YPos", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetChi2LXPos",1096,G__COINCEventDict_656_0_45, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<double,allocator<double> >' 'vector<double>' 0 - newChi2LXPos", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetChi2LYPos",1097,G__COINCEventDict_656_0_46, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<double,allocator<double> >' 'vector<double>' 0 - newChi2LYPos", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetErrInput",1125,G__COINCEventDict_656_0_47, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 - newErrInput", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetErrOutOfRange",1583,G__COINCEventDict_656_0_48, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 - newErrOutOfRange", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetNSlidePos",1181,G__COINCEventDict_656_0_49, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - newNSlidePos", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetEnergyGE",1058,G__COINCEventDict_656_0_50, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - newEnergy", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetEnergyMax",1212,G__COINCEventDict_656_0_51, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - newEnergyMax", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetEnergyFirst",1438,G__COINCEventDict_656_0_52, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - newEnergyFirst", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTimestampGE",1388,G__COINCEventDict_656_0_53, 121, -1, -1, 0, 2, 1, 1, 0, 
"d - - 0 - newTimestamp g - - 0 'false' inNanoSecs", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTimestampT50",1433,G__COINCEventDict_656_0_54, 121, -1, -1, 0, 2, 1, 1, 0, 
"d - - 0 - newTimestampT50 g - - 0 'false' inNanoSecs", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetT50Offset",1100,G__COINCEventDict_656_0_55, 121, -1, -1, 0, 2, 1, 1, 0, 
"d - - 0 - newT50Offset g - - 0 'false' inNanoSecs", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetWFRaw",755,G__COINCEventDict_656_0_56, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<double,allocator<double> >' 'vector<double>' 0 - newWFRaw", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetWFEnergy",1075,G__COINCEventDict_656_0_57, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<double,allocator<double> >' 'vector<double>' 0 - newWFEnergy", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetWFDiff",834,G__COINCEventDict_656_0_58, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<double,allocator<double> >' 'vector<double>' 0 - newWFDiff", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetIMax",667,G__COINCEventDict_656_0_59, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - newIMax", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetChannel",997,G__COINCEventDict_656_0_60, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - newChannel", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CopyEvents",1040,G__COINCEventDict_656_0_61, 121, -1, -1, 0, 2, 1, 1, 0, 
"U 'LYSOEvent' - 0 - newLYSO U 'GEEvent' - 0 - newGE", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CalcT1ToT2TimeNS",1393,G__COINCEventDict_656_0_62, 121, -1, -1, 0, 3, 1, 1, 0, 
"d - - 0 - T1 d - - 0 - T2 "
"d - - 1 - time", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Clear",487,G__COINCEventDict_656_0_63, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__COINCEventDict_656_0_64, 85, G__get_linked_tagnum(&G__COINCEventDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&COINCEvent::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__COINCEventDict_656_0_65, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&COINCEvent::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__COINCEventDict_656_0_66, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&COINCEvent::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__COINCEventDict_656_0_67, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&COINCEvent::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__COINCEventDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__COINCEventDict_656_0_71, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__COINCEventDict_656_0_72, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&COINCEvent::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__COINCEventDict_656_0_73, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&COINCEvent::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__COINCEventDict_656_0_74, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&COINCEvent::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__COINCEventDict_656_0_75, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&COINCEvent::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("COINCEvent", 878, G__COINCEventDict_656_0_76, (int) ('i'), G__get_linked_tagnum(&G__COINCEventDictLN_COINCEvent), -1, 0, 1, 1, 1, 0, "u 'COINCEvent' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~COINCEvent", 1004, G__COINCEventDict_656_0_77, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__COINCEventDict_656_0_78, (int) ('u'), G__get_linked_tagnum(&G__COINCEventDictLN_COINCEvent), -1, 1, 1, 1, 1, 0, "u 'COINCEvent' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncCOINCEventDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {
}

static void G__cpp_setup_global7() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalCOINCEventDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
  G__cpp_setup_global7();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcCOINCEventDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__COINCEventDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__COINCEventDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__COINCEventDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__COINCEventDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__COINCEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__COINCEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__COINCEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__COINCEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__COINCEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__COINCEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__COINCEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__COINCEventDictLN_pairlEunsignedsPintcOintgR = { "pair<unsigned int,int>" , 115 , -1 };
G__linked_taginfo G__COINCEventDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR = { "vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >" , 99 , -1 };
G__linked_taginfo G__COINCEventDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__COINCEventDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__COINCEventDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__COINCEventDictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__COINCEventDictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__COINCEventDictLN_GEEvent = { "GEEvent" , 99 , -1 };
G__linked_taginfo G__COINCEventDictLN_LYSOEvent = { "LYSOEvent" , 99 , -1 };
G__linked_taginfo G__COINCEventDictLN_COINCEvent = { "COINCEvent" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableCOINCEventDict() {
  G__COINCEventDictLN_TClass.tagnum = -1 ;
  G__COINCEventDictLN_TBuffer.tagnum = -1 ;
  G__COINCEventDictLN_TMemberInspector.tagnum = -1 ;
  G__COINCEventDictLN_TObject.tagnum = -1 ;
  G__COINCEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__COINCEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__COINCEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__COINCEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__COINCEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__COINCEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__COINCEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__COINCEventDictLN_pairlEunsignedsPintcOintgR.tagnum = -1 ;
  G__COINCEventDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR.tagnum = -1 ;
  G__COINCEventDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__COINCEventDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__COINCEventDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__COINCEventDictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__COINCEventDictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__COINCEventDictLN_GEEvent.tagnum = -1 ;
  G__COINCEventDictLN_LYSOEvent.tagnum = -1 ;
  G__COINCEventDictLN_COINCEvent.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableCOINCEventDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__COINCEventDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__COINCEventDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__COINCEventDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__COINCEventDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__COINCEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__COINCEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__COINCEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__COINCEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__COINCEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__COINCEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__COINCEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__COINCEventDictLN_pairlEunsignedsPintcOintgR);
   G__get_linked_tagnum_fwd(&G__COINCEventDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__COINCEventDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__COINCEventDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__COINCEventDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__COINCEventDictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__COINCEventDictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__COINCEventDictLN_GEEvent);
   G__get_linked_tagnum_fwd(&G__COINCEventDictLN_LYSOEvent);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__COINCEventDictLN_COINCEvent),sizeof(COINCEvent),-1,324864,(char*)NULL,G__setup_memvarCOINCEvent,G__setup_memfuncCOINCEvent);
}
extern "C" void G__cpp_setupCOINCEventDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupCOINCEventDict()");
  G__set_cpp_environmentCOINCEventDict();
  G__cpp_setup_tagtableCOINCEventDict();

  G__cpp_setup_inheritanceCOINCEventDict();

  G__cpp_setup_typetableCOINCEventDict();

  G__cpp_setup_memvarCOINCEventDict();

  G__cpp_setup_memfuncCOINCEventDict();
  G__cpp_setup_globalCOINCEventDict();
  G__cpp_setup_funcCOINCEventDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncCOINCEventDict();
  return;
}
class G__cpp_setup_initCOINCEventDict {
  public:
    G__cpp_setup_initCOINCEventDict() { G__add_setup_func("COINCEventDict",(G__incsetup)(&G__cpp_setupCOINCEventDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initCOINCEventDict() { G__remove_setup_func("COINCEventDict"); }
};
G__cpp_setup_initCOINCEventDict G__cpp_setup_initializerCOINCEventDict;

