/********************************************************************
* COINCEventDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error COINCEventDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableCOINCEventDict();
extern void G__cpp_setup_inheritanceCOINCEventDict();
extern void G__cpp_setup_typetableCOINCEventDict();
extern void G__cpp_setup_memvarCOINCEventDict();
extern void G__cpp_setup_globalCOINCEventDict();
extern void G__cpp_setup_memfuncCOINCEventDict();
extern void G__cpp_setup_funcCOINCEventDict();
extern void G__set_cpp_environmentCOINCEventDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "COINCEvent.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__COINCEventDictLN_TClass;
extern G__linked_taginfo G__COINCEventDictLN_TBuffer;
extern G__linked_taginfo G__COINCEventDictLN_TMemberInspector;
extern G__linked_taginfo G__COINCEventDictLN_TObject;
extern G__linked_taginfo G__COINCEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__COINCEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__COINCEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__COINCEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__COINCEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__COINCEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__COINCEventDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__COINCEventDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__COINCEventDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__COINCEventDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__COINCEventDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__COINCEventDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__COINCEventDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__COINCEventDictLN_BaseGEEvent;
extern G__linked_taginfo G__COINCEventDictLN_GEEvent;
extern G__linked_taginfo G__COINCEventDictLN_BaseLYSOEvent;
extern G__linked_taginfo G__COINCEventDictLN_LYSOEvent;
extern G__linked_taginfo G__COINCEventDictLN_COINCEvent;

/* STUB derived class for protected member access */
