/********************************************************************
* COINCRunDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error COINCRunDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableCOINCRunDict();
extern void G__cpp_setup_inheritanceCOINCRunDict();
extern void G__cpp_setup_typetableCOINCRunDict();
extern void G__cpp_setup_memvarCOINCRunDict();
extern void G__cpp_setup_globalCOINCRunDict();
extern void G__cpp_setup_memfuncCOINCRunDict();
extern void G__cpp_setup_funcCOINCRunDict();
extern void G__set_cpp_environmentCOINCRunDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "COINCRun.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__COINCRunDictLN_TClass;
extern G__linked_taginfo G__COINCRunDictLN_TBuffer;
extern G__linked_taginfo G__COINCRunDictLN_TMemberInspector;
extern G__linked_taginfo G__COINCRunDictLN_TObject;
extern G__linked_taginfo G__COINCRunDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__COINCRunDictLN_string;
extern G__linked_taginfo G__COINCRunDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__COINCRunDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__COINCRunDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__COINCRunDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__COINCRunDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__COINCRunDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__COINCRunDictLN_TCut;
extern G__linked_taginfo G__COINCRunDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__COINCRunDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__COINCRunDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__COINCRunDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__COINCRunDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__COINCRunDictLN_TH1D;
extern G__linked_taginfo G__COINCRunDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__COINCRunDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__COINCRunDictLN_TH2D;
extern G__linked_taginfo G__COINCRunDictLN_PACSSRun;
extern G__linked_taginfo G__COINCRunDictLN_COINCEvent;
extern G__linked_taginfo G__COINCRunDictLN_COINCRun;

/* STUB derived class for protected member access */
