//
// File generated by rootcint at Fri May 17 11:43:27 2013

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME GEEventDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "GEEventDict.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void GEEvent_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_GEEvent(void *p = 0);
   static void *newArray_GEEvent(Long_t size, void *p);
   static void delete_GEEvent(void *p);
   static void deleteArray_GEEvent(void *p);
   static void destruct_GEEvent(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::GEEvent*)
   {
      ::GEEvent *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::GEEvent >(0);
      static ::ROOT::TGenericClassInfo 
         instance("GEEvent", ::GEEvent::Class_Version(), "./GEEvent.hh", 7,
                  typeid(::GEEvent), DefineBehavior(ptr, ptr),
                  &::GEEvent::Dictionary, isa_proxy, 4,
                  sizeof(::GEEvent) );
      instance.SetNew(&new_GEEvent);
      instance.SetNewArray(&newArray_GEEvent);
      instance.SetDelete(&delete_GEEvent);
      instance.SetDeleteArray(&deleteArray_GEEvent);
      instance.SetDestructor(&destruct_GEEvent);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::GEEvent*)
   {
      return GenerateInitInstanceLocal((::GEEvent*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::GEEvent*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *GEEvent::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *GEEvent::Class_Name()
{
   return "GEEvent";
}

//______________________________________________________________________________
const char *GEEvent::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::GEEvent*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int GEEvent::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::GEEvent*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void GEEvent::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::GEEvent*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *GEEvent::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::GEEvent*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void GEEvent::Streamer(TBuffer &R__b)
{
   // Stream an object of class GEEvent.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(GEEvent::Class(),this);
   } else {
      R__b.WriteClassBuffer(GEEvent::Class(),this);
   }
}

//______________________________________________________________________________
void GEEvent::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class GEEvent.
      TClass *R__cl = ::GEEvent::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "energyFirst", &energyFirst);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "energyMax", &energyMax);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "energy", &energy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "timestamp", &timestamp);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "timestampNS", &timestampNS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "timestampT50", &timestampT50);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "timestampT50NS", &timestampT50NS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "T50Offset", &T50Offset);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "T50OffsetNS", &T50OffsetNS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "wfRaw", (void*)&wfRaw);
      R__insp.InspectMember("vector<double>", (void*)&wfRaw, "wfRaw.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "wfEnergy", (void*)&wfEnergy);
      R__insp.InspectMember("vector<double>", (void*)&wfEnergy, "wfEnergy.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "wfDiff", (void*)&wfDiff);
      R__insp.InspectMember("vector<double>", (void*)&wfDiff, "wfDiff.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "IMax", &IMax);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "channel", &channel);
      PACSSEvent::ShowMembers(R__insp);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_GEEvent(void *p) {
      return  p ? new(p) ::GEEvent : new ::GEEvent;
   }
   static void *newArray_GEEvent(Long_t nElements, void *p) {
      return p ? new(p) ::GEEvent[nElements] : new ::GEEvent[nElements];
   }
   // Wrapper around operator delete
   static void delete_GEEvent(void *p) {
      delete ((::GEEvent*)p);
   }
   static void deleteArray_GEEvent(void *p) {
      delete [] ((::GEEvent*)p);
   }
   static void destruct_GEEvent(void *p) {
      typedef ::GEEvent current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::GEEvent

namespace ROOT {
   void vectorlEdoublegR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEdoublegR_Dictionary();
   static void *new_vectorlEdoublegR(void *p = 0);
   static void *newArray_vectorlEdoublegR(Long_t size, void *p);
   static void delete_vectorlEdoublegR(void *p);
   static void deleteArray_vectorlEdoublegR(void *p);
   static void destruct_vectorlEdoublegR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<double>*)
   {
      vector<double> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<double>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<double>", -2, "vector.dll", 0,
                  typeid(vector<double>), DefineBehavior(ptr, ptr),
                  0, &vectorlEdoublegR_Dictionary, isa_proxy, 0,
                  sizeof(vector<double>) );
      instance.SetNew(&new_vectorlEdoublegR);
      instance.SetNewArray(&newArray_vectorlEdoublegR);
      instance.SetDelete(&delete_vectorlEdoublegR);
      instance.SetDeleteArray(&deleteArray_vectorlEdoublegR);
      instance.SetDestructor(&destruct_vectorlEdoublegR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<double> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<double>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEdoublegR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<double>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlEdoublegR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<double> : new vector<double>;
   }
   static void *newArray_vectorlEdoublegR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<double>[nElements] : new vector<double>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEdoublegR(void *p) {
      delete ((vector<double>*)p);
   }
   static void deleteArray_vectorlEdoublegR(void *p) {
      delete [] ((vector<double>*)p);
   }
   static void destruct_vectorlEdoublegR(void *p) {
      typedef vector<double> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<double>

/********************************************************
* GEEventDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableGEEventDict();

extern "C" void G__set_cpp_environmentGEEventDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("GEEvent.hh");
  G__cpp_reset_tagtableGEEventDict();
}
#include <new>
extern "C" int G__cpp_dllrevGEEventDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* GEEvent */
static int G__GEEventDict_654_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   GEEvent* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new GEEvent[n];
     } else {
       p = new((void*) gvp) GEEvent[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new GEEvent;
     } else {
       p = new((void*) gvp) GEEvent;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__GEEventDictLN_GEEvent));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GEEventDict_654_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GEEvent*) G__getstructoffset())->GetEnergy());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GEEventDict_654_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GEEvent*) G__getstructoffset())->GetEnergyMax());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GEEventDict_654_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GEEvent*) G__getstructoffset())->GetEnergyFirst());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GEEventDict_654_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      G__letdouble(result7, 100, (double) ((GEEvent*) G__getstructoffset())->GetTimestamp((bool) G__int(libp->para[0])));
      break;
   case 0:
      G__letdouble(result7, 100, (double) ((GEEvent*) G__getstructoffset())->GetTimestamp());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GEEventDict_654_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      G__letdouble(result7, 100, (double) ((GEEvent*) G__getstructoffset())->GetTimestampT50((bool) G__int(libp->para[0])));
      break;
   case 0:
      G__letdouble(result7, 100, (double) ((GEEvent*) G__getstructoffset())->GetTimestampT50());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GEEventDict_654_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      G__letdouble(result7, 100, (double) ((GEEvent*) G__getstructoffset())->GetT50Offset((bool) G__int(libp->para[0])));
      break;
   case 0:
      G__letdouble(result7, 100, (double) ((GEEvent*) G__getstructoffset())->GetT50Offset());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GEEventDict_654_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<double>* pobj;
         vector<double> xobj = ((GEEvent*) G__getstructoffset())->GetWFRaw();
         pobj = new vector<double>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GEEventDict_654_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<double>* pobj;
         vector<double> xobj = ((GEEvent*) G__getstructoffset())->GetWFEnergy();
         pobj = new vector<double>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GEEventDict_654_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<double>* pobj;
         vector<double> xobj = ((GEEvent*) G__getstructoffset())->GetWFDiff();
         pobj = new vector<double>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GEEventDict_654_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((GEEvent*) G__getstructoffset())->GetIMax());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GEEventDict_654_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((GEEvent*) G__getstructoffset())->GetChannel());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GEEventDict_654_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GEEvent*) G__getstructoffset())->SetEnergy((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GEEventDict_654_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GEEvent*) G__getstructoffset())->SetEnergyMax((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GEEventDict_654_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GEEvent*) G__getstructoffset())->SetEnergyFirst((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GEEventDict_654_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((GEEvent*) G__getstructoffset())->SetTimestamp((double) G__double(libp->para[0]), (bool) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((GEEvent*) G__getstructoffset())->SetTimestamp((double) G__double(libp->para[0]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GEEventDict_654_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((GEEvent*) G__getstructoffset())->SetTimestampT50((double) G__double(libp->para[0]), (bool) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((GEEvent*) G__getstructoffset())->SetTimestampT50((double) G__double(libp->para[0]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GEEventDict_654_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((GEEvent*) G__getstructoffset())->SetT50Offset((double) G__double(libp->para[0]), (bool) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((GEEvent*) G__getstructoffset())->SetT50Offset((double) G__double(libp->para[0]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GEEventDict_654_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GEEvent*) G__getstructoffset())->SetWFRaw(*((vector<double>*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GEEventDict_654_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GEEvent*) G__getstructoffset())->SetWFEnergy(*((vector<double>*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GEEventDict_654_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GEEvent*) G__getstructoffset())->SetWFDiff(*((vector<double>*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GEEventDict_654_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GEEvent*) G__getstructoffset())->SetIMax((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GEEventDict_654_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GEEvent*) G__getstructoffset())->SetChannel((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GEEventDict_654_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GEEvent*) G__getstructoffset())->CalcT50Offset();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GEEventDict_654_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GEEvent*) G__getstructoffset())->CalcT1ToT2Time((double) G__double(libp->para[0]), (double) G__double(libp->para[1])
, *(int*) G__Intref(&libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GEEventDict_654_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GEEvent*) G__getstructoffset())->CalcT1ToT2TimeNS((double) G__double(libp->para[0]), (double) G__double(libp->para[1])
, *(int*) G__Intref(&libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GEEventDict_654_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GEEvent*) G__getstructoffset())->CalcIMax();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GEEventDict_654_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GEEvent*) G__getstructoffset())->Clear();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GEEventDict_654_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) GEEvent::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GEEventDict_654_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) GEEvent::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GEEventDict_654_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) GEEvent::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GEEventDict_654_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      GEEvent::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GEEventDict_654_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GEEvent*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GEEventDict_654_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) GEEvent::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GEEventDict_654_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) GEEvent::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GEEventDict_654_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) GEEvent::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GEEventDict_654_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) GEEvent::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__GEEventDict_654_0_41(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   GEEvent* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new GEEvent(*(GEEvent*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__GEEventDictLN_GEEvent));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef GEEvent G__TGEEvent;
static int G__GEEventDict_654_0_42(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (GEEvent*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((GEEvent*) (soff+(sizeof(GEEvent)*i)))->~G__TGEEvent();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (GEEvent*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((GEEvent*) (soff))->~G__TGEEvent();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__GEEventDict_654_0_43(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   GEEvent* dest = (GEEvent*) G__getstructoffset();
   *dest = *(GEEvent*) libp->para[0].ref;
   const GEEvent& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* GEEvent */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncGEEventDict {
 public:
  G__Sizep2memfuncGEEventDict(): p(&G__Sizep2memfuncGEEventDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncGEEventDict::*p)();
};

size_t G__get_sizep2memfuncGEEventDict()
{
  G__Sizep2memfuncGEEventDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceGEEventDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__GEEventDictLN_GEEvent))) {
     GEEvent *G__Lderived;
     G__Lderived=(GEEvent*)0x1000;
     {
       PACSSEvent *G__Lpbase=(PACSSEvent*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__GEEventDictLN_GEEvent),G__get_linked_tagnum(&G__GEEventDictLN_PACSSEvent),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__GEEventDictLN_GEEvent),G__get_linked_tagnum(&G__GEEventDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableGEEventDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__GEEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__GEEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GEEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__GEEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GEEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__GEEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__GEEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GEEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__GEEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GEEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__GEEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__GEEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__GEEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__GEEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__GEEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__GEEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__GEEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__GEEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__GEEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<UInt_t,Int_t>",117,G__get_linked_tagnum(&G__GEEventDictLN_pairlEunsignedsPintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__GEEventDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__GEEventDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__GEEventDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GEEventDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__GEEventDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GEEventDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned int,int> >",117,G__get_linked_tagnum(&G__GEEventDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__GEEventDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__GEEventDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__GEEventDictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__GEEventDictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* GEEvent */
static void G__setup_memvarGEEvent(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__GEEventDictLN_GEEvent));
   { GEEvent *p; p=(GEEvent*)0x1000; if (p) { }
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"energyFirst=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"energyMax=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"energy=",0,"energyMax - energyFirst");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"timestamp=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"timestampNS=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"timestampT50=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"timestampT50NS=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"T50Offset=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"T50OffsetNS=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__GEEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,2,"wfRaw=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__GEEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,2,"wfEnergy=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__GEEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,2,"wfDiff=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"IMax=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"channel=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GEEventDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarGEEventDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncGEEvent(void) {
   /* GEEvent */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__GEEventDictLN_GEEvent));
   G__memfunc_setup("GEEvent",654,G__GEEventDict_654_0_1, 105, G__get_linked_tagnum(&G__GEEventDictLN_GEEvent), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetEnergy",906,G__GEEventDict_654_0_2, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetEnergyMax",1200,G__GEEventDict_654_0_3, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetEnergyFirst",1426,G__GEEventDict_654_0_4, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTimestamp",1236,G__GEEventDict_654_0_5, 100, -1, -1, 0, 1, 1, 1, 0, "g - - 0 'false' inNanoSecs", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTimestampT50",1421,G__GEEventDict_654_0_6, 100, -1, -1, 0, 1, 1, 1, 0, "g - - 0 'false' inNanoSecs", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetT50Offset",1088,G__GEEventDict_654_0_7, 100, -1, -1, 0, 1, 1, 1, 0, "g - - 0 'false' inNanoSecs", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetWFRaw",743,G__GEEventDict_654_0_8, 117, G__get_linked_tagnum(&G__GEEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR), G__defined_typename("vector<double>"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetWFEnergy",1063,G__GEEventDict_654_0_9, 117, G__get_linked_tagnum(&G__GEEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR), G__defined_typename("vector<double>"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetWFDiff",822,G__GEEventDict_654_0_10, 117, G__get_linked_tagnum(&G__GEEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR), G__defined_typename("vector<double>"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetIMax",655,G__GEEventDict_654_0_11, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetChannel",985,G__GEEventDict_654_0_12, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetEnergy",918,G__GEEventDict_654_0_13, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - newEnergy", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetEnergyMax",1212,G__GEEventDict_654_0_14, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - newEnergyMax", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetEnergyFirst",1438,G__GEEventDict_654_0_15, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - newEnergyFirst", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTimestamp",1248,G__GEEventDict_654_0_16, 121, -1, -1, 0, 2, 1, 1, 0, 
"d - - 0 - newTimestamp g - - 0 'false' inNanoSecs", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTimestampT50",1433,G__GEEventDict_654_0_17, 121, -1, -1, 0, 2, 1, 1, 0, 
"d - - 0 - newTimestampT50 g - - 0 'false' inNanoSecs", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetT50Offset",1100,G__GEEventDict_654_0_18, 121, -1, -1, 0, 2, 1, 1, 0, 
"d - - 0 - newT50Offset g - - 0 'false' inNanoSecs", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetWFRaw",755,G__GEEventDict_654_0_19, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<double,allocator<double> >' 'vector<double>' 0 - newWFRaw", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetWFEnergy",1075,G__GEEventDict_654_0_20, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<double,allocator<double> >' 'vector<double>' 0 - newWFEnergy", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetWFDiff",834,G__GEEventDict_654_0_21, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<double,allocator<double> >' 'vector<double>' 0 - newWFDiff", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetIMax",667,G__GEEventDict_654_0_22, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - newIMax", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetChannel",997,G__GEEventDict_654_0_23, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - newChannel", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CalcT50Offset",1171,G__GEEventDict_654_0_24, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CalcT1ToT2Time",1232,G__GEEventDict_654_0_25, 121, -1, -1, 0, 3, 1, 1, 0, 
"d - - 0 - fracA d - - 0 - fracB "
"i - - 1 - nSamples", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CalcT1ToT2TimeNS",1393,G__GEEventDict_654_0_26, 121, -1, -1, 0, 3, 1, 1, 0, 
"d - - 0 - fracA d - - 0 - fracB "
"i - - 1 - timeNS", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CalcIMax",738,G__GEEventDict_654_0_27, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Clear",487,G__GEEventDict_654_0_28, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__GEEventDict_654_0_29, 85, G__get_linked_tagnum(&G__GEEventDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&GEEvent::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__GEEventDict_654_0_30, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&GEEvent::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__GEEventDict_654_0_31, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&GEEvent::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__GEEventDict_654_0_32, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&GEEvent::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__GEEventDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__GEEventDict_654_0_36, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__GEEventDict_654_0_37, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&GEEvent::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__GEEventDict_654_0_38, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&GEEvent::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__GEEventDict_654_0_39, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&GEEvent::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__GEEventDict_654_0_40, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&GEEvent::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("GEEvent", 654, G__GEEventDict_654_0_41, (int) ('i'), G__get_linked_tagnum(&G__GEEventDictLN_GEEvent), -1, 0, 1, 1, 1, 0, "u 'GEEvent' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~GEEvent", 780, G__GEEventDict_654_0_42, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__GEEventDict_654_0_43, (int) ('u'), G__get_linked_tagnum(&G__GEEventDictLN_GEEvent), -1, 1, 1, 1, 1, 0, "u 'GEEvent' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncGEEventDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {
}

static void G__cpp_setup_global7() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalGEEventDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
  G__cpp_setup_global7();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcGEEventDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__GEEventDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__GEEventDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__GEEventDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__GEEventDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__GEEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__GEEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__GEEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__GEEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__GEEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__GEEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__GEEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__GEEventDictLN_pairlEunsignedsPintcOintgR = { "pair<unsigned int,int>" , 115 , -1 };
G__linked_taginfo G__GEEventDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR = { "vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >" , 99 , -1 };
G__linked_taginfo G__GEEventDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__GEEventDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__GEEventDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__GEEventDictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__GEEventDictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__GEEventDictLN_PACSSEvent = { "PACSSEvent" , 99 , -1 };
G__linked_taginfo G__GEEventDictLN_GEEvent = { "GEEvent" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableGEEventDict() {
  G__GEEventDictLN_TClass.tagnum = -1 ;
  G__GEEventDictLN_TBuffer.tagnum = -1 ;
  G__GEEventDictLN_TMemberInspector.tagnum = -1 ;
  G__GEEventDictLN_TObject.tagnum = -1 ;
  G__GEEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__GEEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__GEEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__GEEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__GEEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__GEEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__GEEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__GEEventDictLN_pairlEunsignedsPintcOintgR.tagnum = -1 ;
  G__GEEventDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR.tagnum = -1 ;
  G__GEEventDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__GEEventDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__GEEventDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__GEEventDictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__GEEventDictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__GEEventDictLN_PACSSEvent.tagnum = -1 ;
  G__GEEventDictLN_GEEvent.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableGEEventDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__GEEventDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__GEEventDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__GEEventDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__GEEventDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__GEEventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__GEEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__GEEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__GEEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__GEEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__GEEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__GEEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__GEEventDictLN_pairlEunsignedsPintcOintgR);
   G__get_linked_tagnum_fwd(&G__GEEventDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__GEEventDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__GEEventDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__GEEventDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__GEEventDictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__GEEventDictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__GEEventDictLN_PACSSEvent);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__GEEventDictLN_GEEvent),sizeof(GEEvent),-1,292096,(char*)NULL,G__setup_memvarGEEvent,G__setup_memfuncGEEvent);
}
extern "C" void G__cpp_setupGEEventDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupGEEventDict()");
  G__set_cpp_environmentGEEventDict();
  G__cpp_setup_tagtableGEEventDict();

  G__cpp_setup_inheritanceGEEventDict();

  G__cpp_setup_typetableGEEventDict();

  G__cpp_setup_memvarGEEventDict();

  G__cpp_setup_memfuncGEEventDict();
  G__cpp_setup_globalGEEventDict();
  G__cpp_setup_funcGEEventDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncGEEventDict();
  return;
}
class G__cpp_setup_initGEEventDict {
  public:
    G__cpp_setup_initGEEventDict() { G__add_setup_func("GEEventDict",(G__incsetup)(&G__cpp_setupGEEventDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initGEEventDict() { G__remove_setup_func("GEEventDict"); }
};
G__cpp_setup_initGEEventDict G__cpp_setup_initializerGEEventDict;

