/********************************************************************
* GERunDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error GERunDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableGERunDict();
extern void G__cpp_setup_inheritanceGERunDict();
extern void G__cpp_setup_typetableGERunDict();
extern void G__cpp_setup_memvarGERunDict();
extern void G__cpp_setup_globalGERunDict();
extern void G__cpp_setup_memfuncGERunDict();
extern void G__cpp_setup_funcGERunDict();
extern void G__set_cpp_environmentGERunDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "GERun.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__GERunDictLN_TClass;
extern G__linked_taginfo G__GERunDictLN_TBuffer;
extern G__linked_taginfo G__GERunDictLN_TMemberInspector;
extern G__linked_taginfo G__GERunDictLN_TObject;
extern G__linked_taginfo G__GERunDictLN_string;
extern G__linked_taginfo G__GERunDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__GERunDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GERunDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__GERunDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GERunDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__GERunDictLN_TCanvas;
extern G__linked_taginfo G__GERunDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__GERunDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__GERunDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__GERunDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GERunDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__GERunDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__GERunDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__GERunDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__GERunDictLN_GEEvent;
extern G__linked_taginfo G__GERunDictLN_PACSSRun;
extern G__linked_taginfo G__GERunDictLN_GERun;

/* STUB derived class for protected member access */
