/********************************************************************
* LYSORunDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error LYSORunDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableLYSORunDict();
extern void G__cpp_setup_inheritanceLYSORunDict();
extern void G__cpp_setup_typetableLYSORunDict();
extern void G__cpp_setup_memvarLYSORunDict();
extern void G__cpp_setup_globalLYSORunDict();
extern void G__cpp_setup_memfuncLYSORunDict();
extern void G__cpp_setup_funcLYSORunDict();
extern void G__set_cpp_environmentLYSORunDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "LYSORun.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__LYSORunDictLN_TClass;
extern G__linked_taginfo G__LYSORunDictLN_TBuffer;
extern G__linked_taginfo G__LYSORunDictLN_TMemberInspector;
extern G__linked_taginfo G__LYSORunDictLN_TObject;
extern G__linked_taginfo G__LYSORunDictLN_string;
extern G__linked_taginfo G__LYSORunDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__LYSORunDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LYSORunDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__LYSORunDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LYSORunDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__LYSORunDictLN_TCanvas;
extern G__linked_taginfo G__LYSORunDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__LYSORunDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__LYSORunDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__LYSORunDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LYSORunDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__LYSORunDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__LYSORunDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__LYSORunDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__LYSORunDictLN_LYSOEvent;
extern G__linked_taginfo G__LYSORunDictLN_PACSSRun;
extern G__linked_taginfo G__LYSORunDictLN_LYSORun;

/* STUB derived class for protected member access */
