//
// File generated by rootcint at Fri May 17 11:43:28 2013

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME PACSSEventDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "PACSSEventDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void PACSSEvent_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_PACSSEvent(void *p = 0);
   static void *newArray_PACSSEvent(Long_t size, void *p);
   static void delete_PACSSEvent(void *p);
   static void deleteArray_PACSSEvent(void *p);
   static void destruct_PACSSEvent(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::PACSSEvent*)
   {
      ::PACSSEvent *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::PACSSEvent >(0);
      static ::ROOT::TGenericClassInfo 
         instance("PACSSEvent", ::PACSSEvent::Class_Version(), "./PACSSEvent.hh", 32,
                  typeid(::PACSSEvent), DefineBehavior(ptr, ptr),
                  &::PACSSEvent::Dictionary, isa_proxy, 4,
                  sizeof(::PACSSEvent) );
      instance.SetNew(&new_PACSSEvent);
      instance.SetNewArray(&newArray_PACSSEvent);
      instance.SetDelete(&delete_PACSSEvent);
      instance.SetDeleteArray(&deleteArray_PACSSEvent);
      instance.SetDestructor(&destruct_PACSSEvent);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::PACSSEvent*)
   {
      return GenerateInitInstanceLocal((::PACSSEvent*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::PACSSEvent*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *PACSSEvent::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *PACSSEvent::Class_Name()
{
   return "PACSSEvent";
}

//______________________________________________________________________________
const char *PACSSEvent::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::PACSSEvent*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int PACSSEvent::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::PACSSEvent*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void PACSSEvent::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::PACSSEvent*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *PACSSEvent::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::PACSSEvent*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void PACSSEvent::Streamer(TBuffer &R__b)
{
   // Stream an object of class PACSSEvent.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(PACSSEvent::Class(),this);
   } else {
      R__b.WriteClassBuffer(PACSSEvent::Class(),this);
   }
}

//______________________________________________________________________________
void PACSSEvent::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class PACSSEvent.
      TClass *R__cl = ::PACSSEvent::IsA();
      if (R__cl || R__insp.IsA()) { }
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_PACSSEvent(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::PACSSEvent : new ::PACSSEvent;
   }
   static void *newArray_PACSSEvent(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::PACSSEvent[nElements] : new ::PACSSEvent[nElements];
   }
   // Wrapper around operator delete
   static void delete_PACSSEvent(void *p) {
      delete ((::PACSSEvent*)p);
   }
   static void deleteArray_PACSSEvent(void *p) {
      delete [] ((::PACSSEvent*)p);
   }
   static void destruct_PACSSEvent(void *p) {
      typedef ::PACSSEvent current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::PACSSEvent

/********************************************************
* PACSSEventDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablePACSSEventDict();

extern "C" void G__set_cpp_environmentPACSSEventDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("PACSSEvent.hh");
  G__cpp_reset_tagtablePACSSEventDict();
}
#include <new>
extern "C" int G__cpp_dllrevPACSSEventDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* PACSSEvent */
static int G__PACSSEventDict_653_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   PACSSEvent* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new PACSSEvent[n];
     } else {
       p = new((void*) gvp) PACSSEvent[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new PACSSEvent;
     } else {
       p = new((void*) gvp) PACSSEvent;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__PACSSEventDictLN_PACSSEvent));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PACSSEventDict_653_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PACSSEvent*) G__getstructoffset())->ChanNumToXYPos((int) G__int(libp->para[0]), *(int*) G__Intref(&libp->para[1])
, *(int*) G__Intref(&libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PACSSEventDict_653_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) PACSSEvent::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PACSSEventDict_653_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) PACSSEvent::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PACSSEventDict_653_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) PACSSEvent::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PACSSEventDict_653_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      PACSSEvent::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PACSSEventDict_653_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const PACSSEvent*) G__getstructoffset())->IsA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PACSSEventDict_653_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PACSSEvent*) G__getstructoffset())->ShowMembers(*(TMemberInspector*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PACSSEventDict_653_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PACSSEvent*) G__getstructoffset())->Streamer(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PACSSEventDict_653_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PACSSEvent*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PACSSEventDict_653_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) PACSSEvent::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PACSSEventDict_653_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) PACSSEvent::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PACSSEventDict_653_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) PACSSEvent::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PACSSEventDict_653_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) PACSSEvent::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__PACSSEventDict_653_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   PACSSEvent* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new PACSSEvent(*(PACSSEvent*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__PACSSEventDictLN_PACSSEvent));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef PACSSEvent G__TPACSSEvent;
static int G__PACSSEventDict_653_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (PACSSEvent*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((PACSSEvent*) (soff+(sizeof(PACSSEvent)*i)))->~G__TPACSSEvent();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (PACSSEvent*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((PACSSEvent*) (soff))->~G__TPACSSEvent();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__PACSSEventDict_653_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   PACSSEvent* dest = (PACSSEvent*) G__getstructoffset();
   *dest = *(PACSSEvent*) libp->para[0].ref;
   const PACSSEvent& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* PACSSEvent */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncPACSSEventDict {
 public:
  G__Sizep2memfuncPACSSEventDict(): p(&G__Sizep2memfuncPACSSEventDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncPACSSEventDict::*p)();
};

size_t G__get_sizep2memfuncPACSSEventDict()
{
  G__Sizep2memfuncPACSSEventDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancePACSSEventDict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablePACSSEventDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__PACSSEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__PACSSEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PACSSEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__PACSSEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PACSSEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__PACSSEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__PACSSEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PACSSEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__PACSSEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PACSSEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__PACSSEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__PACSSEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__PACSSEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__PACSSEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__PACSSEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__PACSSEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__PACSSEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__PACSSEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__PACSSEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<UInt_t,Int_t>",117,G__get_linked_tagnum(&G__PACSSEventDictLN_pairlEunsignedsPintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__PACSSEventDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__PACSSEventDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__PACSSEventDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PACSSEventDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__PACSSEventDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PACSSEventDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned int,int> >",117,G__get_linked_tagnum(&G__PACSSEventDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__PACSSEventDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__PACSSEventDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__PACSSEventDictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__PACSSEventDictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* PACSSEvent */
static void G__setup_memvarPACSSEvent(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__PACSSEventDictLN_PACSSEvent));
   { PACSSEvent *p; p=(PACSSEvent*)0x1000; if (p) { }
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__PACSSEventDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarPACSSEventDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncPACSSEvent(void) {
   /* PACSSEvent */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__PACSSEventDictLN_PACSSEvent));
   G__memfunc_setup("PACSSEvent",892,G__PACSSEventDict_653_0_1, 105, G__get_linked_tagnum(&G__PACSSEventDictLN_PACSSEvent), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ChanNumToXYPos",1360,G__PACSSEventDict_653_0_2, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - channel i - - 1 - x "
"i - - 1 - y", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__PACSSEventDict_653_0_3, 85, G__get_linked_tagnum(&G__PACSSEventDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&PACSSEvent::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__PACSSEventDict_653_0_4, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&PACSSEvent::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__PACSSEventDict_653_0_5, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&PACSSEvent::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__PACSSEventDict_653_0_6, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&PACSSEvent::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,G__PACSSEventDict_653_0_7, 85, G__get_linked_tagnum(&G__PACSSEventDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,G__PACSSEventDict_653_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,G__PACSSEventDict_653_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__PACSSEventDict_653_0_10, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__PACSSEventDict_653_0_11, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&PACSSEvent::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__PACSSEventDict_653_0_12, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&PACSSEvent::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__PACSSEventDict_653_0_13, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&PACSSEvent::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__PACSSEventDict_653_0_14, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&PACSSEvent::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("PACSSEvent", 892, G__PACSSEventDict_653_0_15, (int) ('i'), G__get_linked_tagnum(&G__PACSSEventDictLN_PACSSEvent), -1, 0, 1, 1, 1, 0, "u 'PACSSEvent' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~PACSSEvent", 1018, G__PACSSEventDict_653_0_16, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__PACSSEventDict_653_0_17, (int) ('u'), G__get_linked_tagnum(&G__PACSSEventDictLN_PACSSEvent), -1, 1, 1, 1, 1, 0, "u 'PACSSEvent' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncPACSSEventDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {
}

static void G__cpp_setup_global7() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalPACSSEventDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
  G__cpp_setup_global7();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcPACSSEventDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__PACSSEventDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__PACSSEventDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__PACSSEventDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__PACSSEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__PACSSEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__PACSSEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__PACSSEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__PACSSEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__PACSSEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__PACSSEventDictLN_pairlEunsignedsPintcOintgR = { "pair<unsigned int,int>" , 115 , -1 };
G__linked_taginfo G__PACSSEventDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR = { "vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >" , 99 , -1 };
G__linked_taginfo G__PACSSEventDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__PACSSEventDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__PACSSEventDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__PACSSEventDictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__PACSSEventDictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__PACSSEventDictLN_PACSSEvent = { "PACSSEvent" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablePACSSEventDict() {
  G__PACSSEventDictLN_TClass.tagnum = -1 ;
  G__PACSSEventDictLN_TBuffer.tagnum = -1 ;
  G__PACSSEventDictLN_TMemberInspector.tagnum = -1 ;
  G__PACSSEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__PACSSEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__PACSSEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__PACSSEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__PACSSEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__PACSSEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__PACSSEventDictLN_pairlEunsignedsPintcOintgR.tagnum = -1 ;
  G__PACSSEventDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR.tagnum = -1 ;
  G__PACSSEventDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__PACSSEventDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__PACSSEventDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__PACSSEventDictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__PACSSEventDictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__PACSSEventDictLN_PACSSEvent.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablePACSSEventDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__PACSSEventDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__PACSSEventDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__PACSSEventDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__PACSSEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__PACSSEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__PACSSEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__PACSSEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__PACSSEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__PACSSEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__PACSSEventDictLN_pairlEunsignedsPintcOintgR);
   G__get_linked_tagnum_fwd(&G__PACSSEventDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__PACSSEventDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__PACSSEventDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__PACSSEventDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__PACSSEventDictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__PACSSEventDictLN_TMatrixTBaselEdoublegR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__PACSSEventDictLN_PACSSEvent),sizeof(PACSSEvent),-1,263424,(char*)NULL,G__setup_memvarPACSSEvent,G__setup_memfuncPACSSEvent);
}
extern "C" void G__cpp_setupPACSSEventDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupPACSSEventDict()");
  G__set_cpp_environmentPACSSEventDict();
  G__cpp_setup_tagtablePACSSEventDict();

  G__cpp_setup_inheritancePACSSEventDict();

  G__cpp_setup_typetablePACSSEventDict();

  G__cpp_setup_memvarPACSSEventDict();

  G__cpp_setup_memfuncPACSSEventDict();
  G__cpp_setup_globalPACSSEventDict();
  G__cpp_setup_funcPACSSEventDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncPACSSEventDict();
  return;
}
class G__cpp_setup_initPACSSEventDict {
  public:
    G__cpp_setup_initPACSSEventDict() { G__add_setup_func("PACSSEventDict",(G__incsetup)(&G__cpp_setupPACSSEventDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initPACSSEventDict() { G__remove_setup_func("PACSSEventDict"); }
};
G__cpp_setup_initPACSSEventDict G__cpp_setup_initializerPACSSEventDict;

