/********************************************************************
* PACSSRunDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error PACSSRunDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablePACSSRunDict();
extern void G__cpp_setup_inheritancePACSSRunDict();
extern void G__cpp_setup_typetablePACSSRunDict();
extern void G__cpp_setup_memvarPACSSRunDict();
extern void G__cpp_setup_globalPACSSRunDict();
extern void G__cpp_setup_memfuncPACSSRunDict();
extern void G__cpp_setup_funcPACSSRunDict();
extern void G__set_cpp_environmentPACSSRunDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "PACSSRun.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__PACSSRunDictLN_TClass;
extern G__linked_taginfo G__PACSSRunDictLN_TBuffer;
extern G__linked_taginfo G__PACSSRunDictLN_TMemberInspector;
extern G__linked_taginfo G__PACSSRunDictLN_TObject;
extern G__linked_taginfo G__PACSSRunDictLN_string;
extern G__linked_taginfo G__PACSSRunDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__PACSSRunDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PACSSRunDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__PACSSRunDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PACSSRunDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__PACSSRunDictLN_TFile;
extern G__linked_taginfo G__PACSSRunDictLN_TTree;
extern G__linked_taginfo G__PACSSRunDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__PACSSRunDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__PACSSRunDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__PACSSRunDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PACSSRunDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__PACSSRunDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__PACSSRunDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__PACSSRunDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__PACSSRunDictLN_PACSSRun;

/* STUB derived class for protected member access */
