/********************************************************************
* ParseGEDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ParseGEDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableParseGEDict();
extern void G__cpp_setup_inheritanceParseGEDict();
extern void G__cpp_setup_typetableParseGEDict();
extern void G__cpp_setup_memvarParseGEDict();
extern void G__cpp_setup_globalParseGEDict();
extern void G__cpp_setup_memfuncParseGEDict();
extern void G__cpp_setup_funcParseGEDict();
extern void G__set_cpp_environmentParseGEDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "ParseGE.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__ParseGEDictLN_TClass;
extern G__linked_taginfo G__ParseGEDictLN_TBuffer;
extern G__linked_taginfo G__ParseGEDictLN_TMemberInspector;
extern G__linked_taginfo G__ParseGEDictLN_basic_ifstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__ParseGEDictLN_string;
extern G__linked_taginfo G__ParseGEDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__ParseGEDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ParseGEDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__ParseGEDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ParseGEDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__ParseGEDictLN_TFile;
extern G__linked_taginfo G__ParseGEDictLN_TTree;
extern G__linked_taginfo G__ParseGEDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__ParseGEDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__ParseGEDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__ParseGEDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ParseGEDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__ParseGEDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__ParseGEDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__ParseGEDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__ParseGEDictLN_GEEvent;
extern G__linked_taginfo G__ParseGEDictLN_ParseGE;

/* STUB derived class for protected member access */
