//
// File generated by rootcint at Fri May 17 11:43:29 2013

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME ParseLYSODict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "ParseLYSODict.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void ParseLYSO_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_ParseLYSO(void *p = 0);
   static void *newArray_ParseLYSO(Long_t size, void *p);
   static void delete_ParseLYSO(void *p);
   static void deleteArray_ParseLYSO(void *p);
   static void destruct_ParseLYSO(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::ParseLYSO*)
   {
      ::ParseLYSO *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::ParseLYSO >(0);
      static ::ROOT::TGenericClassInfo 
         instance("ParseLYSO", ::ParseLYSO::Class_Version(), "./ParseLYSO.hh", 9,
                  typeid(::ParseLYSO), DefineBehavior(ptr, ptr),
                  &::ParseLYSO::Dictionary, isa_proxy, 4,
                  sizeof(::ParseLYSO) );
      instance.SetNew(&new_ParseLYSO);
      instance.SetNewArray(&newArray_ParseLYSO);
      instance.SetDelete(&delete_ParseLYSO);
      instance.SetDeleteArray(&deleteArray_ParseLYSO);
      instance.SetDestructor(&destruct_ParseLYSO);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::ParseLYSO*)
   {
      return GenerateInitInstanceLocal((::ParseLYSO*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::ParseLYSO*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *ParseLYSO::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *ParseLYSO::Class_Name()
{
   return "ParseLYSO";
}

//______________________________________________________________________________
const char *ParseLYSO::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::ParseLYSO*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int ParseLYSO::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::ParseLYSO*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void ParseLYSO::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::ParseLYSO*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *ParseLYSO::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::ParseLYSO*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void ParseLYSO::Streamer(TBuffer &R__b)
{
   // Stream an object of class ParseLYSO.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(ParseLYSO::Class(),this);
   } else {
      R__b.WriteClassBuffer(ParseLYSO::Class(),this);
   }
}

//______________________________________________________________________________
void ParseLYSO::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class ParseLYSO.
      TClass *R__cl = ::ParseLYSO::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "inFileName", (void*)&inFileName);
      R__insp.InspectMember("string", (void*)&inFileName, "inFileName.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "outFileName", (void*)&outFileName);
      R__insp.InspectMember("string", (void*)&outFileName, "outFileName.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "inFile", (void*)&inFile);
      R__insp.InspectMember("ifstream", (void*)&inFile, "inFile.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*rootFile", &rootFile);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*eventTree", &eventTree);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "word", &word);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*event", &event);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "lastVertTimestamp", &lastVertTimestamp);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "lastRealTimestamp", &lastRealTimestamp);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "numCurrEvent", &numCurrEvent);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "numTotalEvents", &numTotalEvents);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "inputError", &inputError);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nInputError", &nInputError);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "outOfRange", &outOfRange);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nOutOfRange", &nOutOfRange);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "numSlidePositions", &numSlidePositions);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "gainCorrect", (void*)&gainCorrect);
      R__insp.InspectMember("vector<double>", (void*)&gainCorrect, "gainCorrect.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "error", &error);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_ParseLYSO(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::ParseLYSO : new ::ParseLYSO;
   }
   static void *newArray_ParseLYSO(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::ParseLYSO[nElements] : new ::ParseLYSO[nElements];
   }
   // Wrapper around operator delete
   static void delete_ParseLYSO(void *p) {
      delete ((::ParseLYSO*)p);
   }
   static void deleteArray_ParseLYSO(void *p) {
      delete [] ((::ParseLYSO*)p);
   }
   static void destruct_ParseLYSO(void *p) {
      typedef ::ParseLYSO current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::ParseLYSO

namespace ROOT {
   void vectorlEdoublegR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEdoublegR_Dictionary();
   static void *new_vectorlEdoublegR(void *p = 0);
   static void *newArray_vectorlEdoublegR(Long_t size, void *p);
   static void delete_vectorlEdoublegR(void *p);
   static void deleteArray_vectorlEdoublegR(void *p);
   static void destruct_vectorlEdoublegR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<double>*)
   {
      vector<double> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<double>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<double>", -2, "vector.dll", 0,
                  typeid(vector<double>), DefineBehavior(ptr, ptr),
                  0, &vectorlEdoublegR_Dictionary, isa_proxy, 0,
                  sizeof(vector<double>) );
      instance.SetNew(&new_vectorlEdoublegR);
      instance.SetNewArray(&newArray_vectorlEdoublegR);
      instance.SetDelete(&delete_vectorlEdoublegR);
      instance.SetDeleteArray(&deleteArray_vectorlEdoublegR);
      instance.SetDestructor(&destruct_vectorlEdoublegR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<double> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<double>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEdoublegR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<double>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlEdoublegR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<double> : new vector<double>;
   }
   static void *newArray_vectorlEdoublegR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<double>[nElements] : new vector<double>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEdoublegR(void *p) {
      delete ((vector<double>*)p);
   }
   static void deleteArray_vectorlEdoublegR(void *p) {
      delete [] ((vector<double>*)p);
   }
   static void destruct_vectorlEdoublegR(void *p) {
      typedef vector<double> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<double>

/********************************************************
* ParseLYSODict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableParseLYSODict();

extern "C" void G__set_cpp_environmentParseLYSODict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("ParseLYSO.hh");
  G__cpp_reset_tagtableParseLYSODict();
}
#include <new>
extern "C" int G__cpp_dllrevParseLYSODict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* ParseLYSO */
static int G__ParseLYSODict_655_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   ParseLYSO* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new ParseLYSO[n];
     } else {
       p = new((void*) gvp) ParseLYSO[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new ParseLYSO;
     } else {
       p = new((void*) gvp) ParseLYSO;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__ParseLYSODictLN_ParseLYSO));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ParseLYSODict_655_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   ParseLYSO* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 3
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new ParseLYSO(
*((string*) G__int(libp->para[0])), *((string*) G__int(libp->para[1]))
, (int) G__int(libp->para[2]));
   } else {
     p = new((void*) gvp) ParseLYSO(
*((string*) G__int(libp->para[0])), *((string*) G__int(libp->para[1]))
, (int) G__int(libp->para[2]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__ParseLYSODictLN_ParseLYSO));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ParseLYSODict_655_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((ParseLYSO*) G__getstructoffset())->ReadAllEvents());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ParseLYSODict_655_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ParseLYSO::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ParseLYSODict_655_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ParseLYSO::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ParseLYSODict_655_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) ParseLYSO::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ParseLYSODict_655_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ParseLYSO::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ParseLYSODict_655_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const ParseLYSO*) G__getstructoffset())->IsA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ParseLYSODict_655_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ParseLYSO*) G__getstructoffset())->ShowMembers(*(TMemberInspector*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ParseLYSODict_655_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ParseLYSO*) G__getstructoffset())->Streamer(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ParseLYSODict_655_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ParseLYSO*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ParseLYSODict_655_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ParseLYSO::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ParseLYSODict_655_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ParseLYSO::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ParseLYSODict_655_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ParseLYSO::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ParseLYSODict_655_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ParseLYSO::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef ParseLYSO G__TParseLYSO;
static int G__ParseLYSODict_655_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (ParseLYSO*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((ParseLYSO*) (soff+(sizeof(ParseLYSO)*i)))->~G__TParseLYSO();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (ParseLYSO*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((ParseLYSO*) (soff))->~G__TParseLYSO();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* ParseLYSO */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncParseLYSODict {
 public:
  G__Sizep2memfuncParseLYSODict(): p(&G__Sizep2memfuncParseLYSODict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncParseLYSODict::*p)();
};

size_t G__get_sizep2memfuncParseLYSODict()
{
  G__Sizep2memfuncParseLYSODict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceParseLYSODict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableParseLYSODict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__ParseLYSODictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ParseLYSODictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ParseLYSODictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ParseLYSODictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ParseLYSODictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__ParseLYSODictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ParseLYSODictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ParseLYSODictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ParseLYSODictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ParseLYSODictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__ParseLYSODictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__ParseLYSODictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__ParseLYSODictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__ParseLYSODictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__ParseLYSODictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__ParseLYSODictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__ParseLYSODictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__ParseLYSODictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__ParseLYSODictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<UInt_t,Int_t>",117,G__get_linked_tagnum(&G__ParseLYSODictLN_pairlEunsignedsPintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__ParseLYSODictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__ParseLYSODictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ParseLYSODictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ParseLYSODictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ParseLYSODictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ParseLYSODictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned int,int> >",117,G__get_linked_tagnum(&G__ParseLYSODictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__ParseLYSODictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__ParseLYSODictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__ParseLYSODictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__ParseLYSODictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* ParseLYSO */
static void G__setup_memvarParseLYSO(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__ParseLYSODictLN_ParseLYSO));
   { ParseLYSO *p; p=(ParseLYSO*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__ParseLYSODictLN_string),-1,-1,2,"inFileName=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__ParseLYSODictLN_string),-1,-1,2,"outFileName=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__ParseLYSODictLN_basic_ifstreamlEcharcOchar_traitslEchargRsPgR),G__defined_typename("ifstream"),-1,2,"inFile=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ParseLYSODictLN_TFile),-1,-1,2,"rootFile=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ParseLYSODictLN_TTree),-1,-1,2,"eventTree=",0,(char*)NULL);
   G__memvar_setup((void*)0,114,0,0,-1,G__defined_typename("uint16_t"),-1,2,"word=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ParseLYSODictLN_LYSOEvent),-1,-1,2,"event=",0,(char*)NULL);
   G__memvar_setup((void*)0,104,0,0,-1,G__defined_typename("uint32_t"),-1,2,"lastVertTimestamp=",0,"For the clock reset problem");
   G__memvar_setup((void*)0,107,0,0,-1,G__defined_typename("uint64_t"),-1,2,"lastRealTimestamp=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"numCurrEvent=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"numTotalEvents=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,2,"inputError=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"nInputError=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,2,"outOfRange=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"nOutOfRange=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"numSlidePositions=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__ParseLYSODictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,2,"gainCorrect=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->error)-(long)(p)),103,0,0,-1,-1,-1,1,"error=",0,(char*)NULL);
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ParseLYSODictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarParseLYSODict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncParseLYSO(void) {
   /* ParseLYSO */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__ParseLYSODictLN_ParseLYSO));
   G__memfunc_setup("OpenLYSOFile",1113,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("OpenROOTFile",1110,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("LoadGainCorrection",1815,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ReadWord",792,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ReadFileHeader",1349,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ReadEvent",894,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("EndianSwap",1002,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 2, 0, "r - 'uint16_t' 1 - bitsToSwap", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ParseLYSO",834,G__ParseLYSODict_655_0_8, 105, G__get_linked_tagnum(&G__ParseLYSODictLN_ParseLYSO), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ParseLYSO",834,G__ParseLYSODict_655_0_9, 105, G__get_linked_tagnum(&G__ParseLYSODictLN_ParseLYSO), -1, 0, 3, 1, 1, 0, 
"u 'string' - 0 - newInFileName u 'string' - 0 - newOutFileName "
"i - - 0 - nPositions", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ReadAllEvents",1290,G__ParseLYSODict_655_0_10, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__ParseLYSODict_655_0_11, 85, G__get_linked_tagnum(&G__ParseLYSODictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&ParseLYSO::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__ParseLYSODict_655_0_12, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&ParseLYSO::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__ParseLYSODict_655_0_13, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&ParseLYSO::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__ParseLYSODict_655_0_14, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&ParseLYSO::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,G__ParseLYSODict_655_0_15, 85, G__get_linked_tagnum(&G__ParseLYSODictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,G__ParseLYSODict_655_0_16, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,G__ParseLYSODict_655_0_17, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__ParseLYSODict_655_0_18, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__ParseLYSODict_655_0_19, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&ParseLYSO::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__ParseLYSODict_655_0_20, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&ParseLYSO::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__ParseLYSODict_655_0_21, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&ParseLYSO::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__ParseLYSODict_655_0_22, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&ParseLYSO::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~ParseLYSO", 960, G__ParseLYSODict_655_0_23, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncParseLYSODict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {
}

static void G__cpp_setup_global7() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalParseLYSODict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
  G__cpp_setup_global7();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcParseLYSODict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__ParseLYSODictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__ParseLYSODictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__ParseLYSODictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__ParseLYSODictLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__ParseLYSODictLN_basic_ifstreamlEcharcOchar_traitslEchargRsPgR = { "basic_ifstream<char,char_traits<char> >" , 99 , -1 };
G__linked_taginfo G__ParseLYSODictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__ParseLYSODictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__ParseLYSODictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ParseLYSODictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__ParseLYSODictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ParseLYSODictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__ParseLYSODictLN_TFile = { "TFile" , 99 , -1 };
G__linked_taginfo G__ParseLYSODictLN_TTree = { "TTree" , 99 , -1 };
G__linked_taginfo G__ParseLYSODictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__ParseLYSODictLN_pairlEunsignedsPintcOintgR = { "pair<unsigned int,int>" , 115 , -1 };
G__linked_taginfo G__ParseLYSODictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR = { "vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >" , 99 , -1 };
G__linked_taginfo G__ParseLYSODictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__ParseLYSODictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__ParseLYSODictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__ParseLYSODictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__ParseLYSODictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__ParseLYSODictLN_LYSOEvent = { "LYSOEvent" , 99 , -1 };
G__linked_taginfo G__ParseLYSODictLN_ParseLYSO = { "ParseLYSO" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableParseLYSODict() {
  G__ParseLYSODictLN_TClass.tagnum = -1 ;
  G__ParseLYSODictLN_TBuffer.tagnum = -1 ;
  G__ParseLYSODictLN_TMemberInspector.tagnum = -1 ;
  G__ParseLYSODictLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__ParseLYSODictLN_basic_ifstreamlEcharcOchar_traitslEchargRsPgR.tagnum = -1 ;
  G__ParseLYSODictLN_string.tagnum = -1 ;
  G__ParseLYSODictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__ParseLYSODictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ParseLYSODictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__ParseLYSODictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ParseLYSODictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__ParseLYSODictLN_TFile.tagnum = -1 ;
  G__ParseLYSODictLN_TTree.tagnum = -1 ;
  G__ParseLYSODictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__ParseLYSODictLN_pairlEunsignedsPintcOintgR.tagnum = -1 ;
  G__ParseLYSODictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR.tagnum = -1 ;
  G__ParseLYSODictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ParseLYSODictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__ParseLYSODictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__ParseLYSODictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__ParseLYSODictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__ParseLYSODictLN_LYSOEvent.tagnum = -1 ;
  G__ParseLYSODictLN_ParseLYSO.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableParseLYSODict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__ParseLYSODictLN_TClass);
   G__get_linked_tagnum_fwd(&G__ParseLYSODictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__ParseLYSODictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__ParseLYSODictLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__ParseLYSODictLN_basic_ifstreamlEcharcOchar_traitslEchargRsPgR);
   G__get_linked_tagnum_fwd(&G__ParseLYSODictLN_string);
   G__get_linked_tagnum_fwd(&G__ParseLYSODictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__ParseLYSODictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ParseLYSODictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__ParseLYSODictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ParseLYSODictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__ParseLYSODictLN_TFile);
   G__get_linked_tagnum_fwd(&G__ParseLYSODictLN_TTree);
   G__get_linked_tagnum_fwd(&G__ParseLYSODictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__ParseLYSODictLN_pairlEunsignedsPintcOintgR);
   G__get_linked_tagnum_fwd(&G__ParseLYSODictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__ParseLYSODictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ParseLYSODictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ParseLYSODictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__ParseLYSODictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__ParseLYSODictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__ParseLYSODictLN_LYSOEvent);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__ParseLYSODictLN_ParseLYSO),sizeof(ParseLYSO),-1,296192,(char*)NULL,G__setup_memvarParseLYSO,G__setup_memfuncParseLYSO);
}
extern "C" void G__cpp_setupParseLYSODict(void) {
  G__check_setup_version(30051515,"G__cpp_setupParseLYSODict()");
  G__set_cpp_environmentParseLYSODict();
  G__cpp_setup_tagtableParseLYSODict();

  G__cpp_setup_inheritanceParseLYSODict();

  G__cpp_setup_typetableParseLYSODict();

  G__cpp_setup_memvarParseLYSODict();

  G__cpp_setup_memfuncParseLYSODict();
  G__cpp_setup_globalParseLYSODict();
  G__cpp_setup_funcParseLYSODict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncParseLYSODict();
  return;
}
class G__cpp_setup_initParseLYSODict {
  public:
    G__cpp_setup_initParseLYSODict() { G__add_setup_func("ParseLYSODict",(G__incsetup)(&G__cpp_setupParseLYSODict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initParseLYSODict() { G__remove_setup_func("ParseLYSODict"); }
};
G__cpp_setup_initParseLYSODict G__cpp_setup_initializerParseLYSODict;

